# Generated by Django 3.2.7 on 2021-10-14 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesh', '0005_auto_20211007_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='repetitions',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='sets',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
