# Generated by Django 3.2.7 on 2021-11-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesh', '0007_session_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='last_workout',
            field=models.DateTimeField(null=True),
        ),
    ]
