# Generated by Django 3.2.7 on 2021-10-03 06:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sesh', '0002_auto_20210929_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='duration',
        ),
        migrations.AddField(
            model_name='session',
            name='finish_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
