# Generated by Django 3.2.7 on 2021-10-06 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesh', '0003_auto_20211003_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='finish_time',
        ),
        migrations.RemoveField(
            model_name='session',
            name='start_time',
        ),
        migrations.AddField(
            model_name='session',
            name='duration',
            field=models.DurationField(null=True),
        ),
    ]
