# Generated by Django 3.2.7 on 2021-10-07 13:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesh', '0004_auto_20211006_1114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='description',
            new_name='notes',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='repetitions',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinLengthValidator(1, 'Number of repetitions must be at least 1.')]),
        ),
    ]
