# Generated by Django 3.2.7 on 2021-10-17 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesh', '0006_auto_20211014_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
